* Input and Output

Lisp의 모든 입출력은 Stream을 통해 이루어진다. Stream은 터미널, 파일,
소켓, 문자열에 대한 출력 함수의 공통 라이브러리를 지원하는 추상화이다.

기본적으로 특정 스트림을 지정하지않으면 기본 입력은 =*standard-input*=
이며, 출력은 =*standard-output*= 이다. 이들 기본 스트림은 List
리스너에 연결되어있다.

** 입력기능

=read= 함수는 Lisp 표현식 하나를 읽어들일 때 수행된다. 개행 문자는
무시하고 표현식을 하나씩 들어들이는데, 아래 예제를 통해 확인이 가능하다.

예를 들어 =test.dat= 라는 파일에 다음과 같은 내용을 넣어두자.

#+BEGIN_SRC

1 2 3
4 "the cat bit the rat"
        read with-open-file

#+END_SRC

이제 아래와 같이 프로그램을 작성한다.

#+BEGIN_SRC lisp

  (defun read-test-1 ()
    (with-open-file
      (input-stream "test.dat" :direction :input)
      (dotimes (i 1000)
        (let ((x (read input-stream nil nil)))
          (if (null x) (return))
          (format t "next expression in file: ~S~%" x)))))

#+END_SRC

SBCL에서 현재 경로를 옮기려면 =(sb-posix:chdir "/path/to/work/dir")=
이라고 하면 된다. 현재 경로를 확인하는 방법은 =(sb-posix:getcwd)= 라고
한다.

실행결과는

#+BEGIN_SRC

next expression in file: 1
next expression in file: 2
next expression in file: 3
next expression in file: 4
next expression in file: "the cat bit the rat"
next expression in file: READ
next expression in file: WITH-OPEN-FILE
NIL

#+END_SRC

이다.

경로 정보를 더 섬세하게 작성하려면 =make-pathname= 함수를
사용한다. 아래 예에서는 =testdata/test.dat= 를 지정한다.

#+BEGIN_SRC lisp


  (let ((a-path-name
          (make-pathname :directory "testdata"
                         :name "test.dat")))
    (with-open-file
      (input-stream a-path-name :direction :input)
      ...
      ))

#+END_SRC


** read-line

=readline= 은 한 문장씩 읽어들이는 함수이다.

#+BEGIN_SRC lisp

  (defun readline-test ()
    "read a maximum of 1000 expressions from the file 'test.dat'"
    (with-open-file
      (input-stream "test.dat" :direction :input)
      (dotimes (i 1000)
        (let ((x (read-line input-stream nil nil)))
          (if (null x) (return))
          (format t "next line in file: ~S~%" x)))))

#+END_SRC

** 문자열을 Stream 으로 사용하기

=with-input-from-string= 매크로를 이용하면 문자열을 스트림으로 이용할 수 있다.

#+BEGIN_SRC lisp

  (defun read-from-string-test ()
    (let ((str "1 2 \"My Parrot is named Brady.\" (11 22)"))
      (with-input-from-string
        (input-stream str)
        (dotimes (i 1000)
          (let ((x (read input-stream nil nil)))
            (if (null x) (return))
            (format t "next expression in string: ~S~%"))))))

#+END_SRC


* Printing

지금까지는 =format= 함수에 첫번째 파라미터를 =t= 로 하여
사용했다. 원래 이 자리는 스트림 값이 오는 곳으로 =t= 는
=*standard-output*= 을 의미한다. 해당 값 대신 =nil= 을 넣으면 문자열로
반환하라는 의미가 된다.

#+BEGIN_SRC lisp

  (let ((l1 '(1 2))
        (x 3.14159))
    (format nil ("~A~A" l1 x)))

#+END_SRC

=print= 와 =princ= 는 인자를 받는 면에서는 같지만, =print= 는 리습
객체를 반환하고, =princ= 는 사람에게 더 맞춰진 결과를 준다는 면에서
차이가 있다.

#+BEGIN_SRC lisp

  ;; 출력되는 값은 "testing" 이다.
  (print "testing")

  ;; 출력되는 값은 testing 이다
  (princ "testing")
  
#+END_SRC

파일에 출력하기위해서는 =with-open-file= 매트로를 이용한다.

#+BEGIN_SRC lisp

  (with-open-file
    (out-stream "test1.dat"
                :direction :output
                :if-exists :supersede)
    (print "the cat ran down the road" out-stream)
    (format out-stream "1 + 2 is: ~A~%" (+ 1 2))
    (princ "Stocking!!" out-stream)
    (terpri out-stream))
  
#+END_SRC

=princ= 는 개행문자를 출력하지않기 때문에 =terpri= 와 자주 사용된다.
